{{ config(materialized='table') }}

SELECT
    CITY,
    WEATHER_DATE,
    MIN(WEATHER_TIME) AS FIRST_HOUR,
    MAX(WEATHER_TIME) AS LAST_HOUR,
    COUNT(*) AS HOURLY_OBSERVATIONS,
    AVG(TEMPERATURE_C) AS AVG_TEMPERATURE_C,
    MIN(TEMPERATURE_C) AS MIN_TEMPERATURE_C,
    MAX(TEMPERATURE_C) AS MAX_TEMPERATURE_C,
    AVG(RELATIVE_HUMIDITY_PCT) AS AVG_RELATIVE_HUMIDITY_PCT,
    SUM(PRECIPITATION_MM) AS TOTAL_PRECIPITATION_MM,
    SUM(RAIN_MM) AS TOTAL_RAIN_MM,
    AVG(WIND_SPEED_KMH) AS AVG_WIND_SPEED_KMH,
    MAX(WIND_SPEED_KMH) AS MAX_WIND_SPEED_KMH
FROM {{ ref('stg_raw_weather') }}
GROUP BY CITY, WEATHER_DATE