{{ config(materialized='view') }}

SELECT
    CITY::VARCHAR AS CITY,
    LATITUDE::FLOAT AS LATITUDE,
    LONGITUDE::FLOAT AS LONGITUDE,
    WEATHER_TIME::TIMESTAMP_NTZ AS WEATHER_TIME,
    TO_DATE(WEATHER_TIME) AS WEATHER_DATE,
    TEMPERATURE_C::FLOAT AS TEMPERATURE_C,
    RELATIVE_HUMIDITY_PCT::FLOAT AS RELATIVE_HUMIDITY_PCT,
    PRECIPITATION_MM::FLOAT AS PRECIPITATION_MM,
    RAIN_MM::FLOAT AS RAIN_MM,
    WIND_SPEED_KMH::FLOAT AS WIND_SPEED_KMH,
    WEATHER_CODE::INTEGER AS WEATHER_CODE,
    LOADED_AT::TIMESTAMP_NTZ AS LOADED_AT
FROM {{ source('raw', 'RAW_WEATHER') }}
WHERE CITY IS NOT NULL
  AND WEATHER_TIME IS NOT NULL