-- A-side Snowflake objects
-- Run this once before enabling the Airflow DAG.

CREATE DATABASE IF NOT EXISTS WEATHER_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS WEATHER_ANALYTICS.RAW;

USE DATABASE WEATHER_ANALYTICS;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_WEATHER (
    CITY VARCHAR(100) NOT NULL,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    WEATHER_TIME TIMESTAMP_NTZ NOT NULL,
    TEMPERATURE_C FLOAT,
    RELATIVE_HUMIDITY_PCT FLOAT,
    PRECIPITATION_MM FLOAT,
    RAIN_MM FLOAT,
    WIND_SPEED_KMH FLOAT,
    WEATHER_CODE INTEGER,
    LOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    -- Snowflake standard-table constraints are informational rather than
    -- the mechanism used here for duplicate prevention.
    CONSTRAINT PK_RAW_WEATHER PRIMARY KEY (CITY, WEATHER_TIME)
);

-- Optional validation queries
SELECT COUNT(*) AS ROW_COUNT FROM RAW_WEATHER;

SELECT CITY, MIN(WEATHER_TIME), MAX(WEATHER_TIME), COUNT(*) AS ROW_COUNT
FROM RAW_WEATHER
GROUP BY CITY
ORDER BY CITY;

SELECT CITY, WEATHER_TIME, COUNT(*) AS C
FROM RAW_WEATHER
GROUP BY CITY, WEATHER_TIME
HAVING COUNT(*) > 1;
